---
name: Release

on:
  push:
    branches: [ main ]
    tags:
      - v*

jobs:
  release:
    name: Released on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Caching
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: ${{matrix.os}}-bazel
      - name: Install
        run: make install
      - name: Build
        run: make build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: reclient-artifact
          path: |
            bazel-bin/cmd/bootstrap/bootstrap_/bootstrap
            bazel-bin/cmd/dumpstats/dumpstats_/dumpstats
            bazel-bin/cmd/reproxy/reproxy_/reproxy
            bazel-bin/cmd/rewrapper/rewrapper_/rewrapper
            bazel-bin/cmd/scandeps/scandeps_server_/scandeps_server
  push:
    name: Pushed on ${{matrix.os}}
    needs: [ release ]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: reclient-artifact
      - name: Push
        run: |
          git clone https://gitee.com/distbuild/reclient-release.git
          git config --global user.name "craftslab"
          git config --global user.email "angersax@sina.com"
          cp -r bootstrap/bootstrap_/bootstrap dumpstats/dumpstats_/dumpstats reproxy/reproxy_/reproxy rewrapper/rewrapper_/rewrapper -t reclient-release
          pushd reclient-release || exit 1
          git add .
          git commit -m "feat[gh]: updated from https://github.com/${{github.repository}}/commit/${{github.sha}}"
          git push https://craftslab:${{ secrets.GITEE_DISTBUILD_TOKEN }}@gitee.com/distbuild/reclient-release.git --all
          popd || exit 1
